# Generated by Django 3.2.4 on 2021-06-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0002_jobad'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.jobad')),
                ('job_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.jobcandidate')),
            ],
        ),
    ]
