# Generated by Django 3.2.4 on 2021-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidate',
            name='applied_for_job_ad',
            field=models.ManyToManyField(to='agency_api.JobAd'),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
