# Generated by Django 3.2.4 on 2021-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0004_auto_20210624_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcandidate',
            name='applied_for_job_ad',
            field=models.ManyToManyField(blank=True, to='agency_api.JobAd'),
        ),
    ]
